version: '3.9'
services:

  api:
    env_file:
      - ./.production.env
    build: .
    restart: unless-stopped
    ports:
      - "${PORT_EXPOSE}:${PORT}"
    networks:
      - mynet
networks:
  mynet:
